# Generated by Django 4.1 on 2022-08-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=250)),
                ('game_genre', models.CharField(max_length=200)),
                ('game_release_year', models.DateField(blank=True, null=True)),
                ('game_collection', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=250)),
                ('movie_genre', models.CharField(max_length=200)),
                ('movie_release_year', models.DateField(blank=True, null=True)),
                ('movie_collection', models.CharField(max_length=350)),
            ],
        ),
    ]
