# Generated by Django 4.1 on 2022-08-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_system',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
