# Generated by Django 4.1 on 2022-08-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_game_game_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_release_year',
            field=models.CharField(default=None, max_length=4),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_release_year',
            field=models.CharField(default=None, max_length=4),
        ),
    ]
